<?php

namespace School\MainBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class TeacherController__JMSInjector
{
    public static function inject($container) {
        $instance = new \School\MainBundle\Controller\TeacherController();
        return $instance;
    }
}
